### ISSUE TITLE
 Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String, RestSharp.FileParameterOptions)'.

### ISSUE THREAD

**Issue by eckhor84** [ElasticEmail/elasticemail-csharp#3]
i am trying to send transactional mail using EmailsTransactionalPostWithHttpInfoAsync method but keep getting " Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String, RestSharp.FileParameterOptions)'." error.

	<ItemGroup>
		<PackageReference Include="ElasticEmail" Version="4.0.23" />
		<PackageReference Include="JsonSubTypes" Version="2.0.1" />
		<PackageReference Include="Mailjet.Api" Version="3.0.0" />
		<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
		
		<PackageReference Include="Hangfire.Core" Version="1.8.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RestSharp" Version="110.2.0" />
		<PackageReference Include="Polly" Version="8.2.0" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
	</ItemGroup>

**Comment by Solnake** [comment]
The issue with the new version of RestSharp where the extension method was changed from 
```
public static RestRequest AddFile(
        this RestRequest      request,
        string                name,
        byte[]                bytes,
        string                filename,
        string?               contentType = null,
        FileParameterOptions? options     = null
    )
```

to 
```
public static RestRequest AddFile(
        this RestRequest      request,
        string                name,
        byte[]                bytes,
        string                fileName,
        ContentType?          contentType = null,
        FileParameterOptions? options     = null
    )
```

@ElasticEmail will do you something to fix it?

**Comment by radzawee** [comment]
ElasticEmail C# library has been generated using OpenAPI Generator, based on RestSharp 106.13.0. We'll take a look at the latest generator, which is using version 110.2.0, and update the library.

**Comment by radzawee** [comment]
Library has been updated, using OpenAPI Generator 7.7.0.
